name: streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - google-generativeai
    - requests
    - pandas
    - python-dotenv
    - scikit-learn==1.3.2
    - joblib
    - beautifulsoup4
    - xgboost
    - lightgbm
    - playwright
